### PR TITLE
delete duplicated data

### PR DESCRIPTION
**Pull request by balthild**
Some states and cities data are obsolete, I've deleted it.

### CODE REVIEW

**Comment by javydreamercsw** [comment]
It looks clean besides I haven't checked the reason behind them being obsolete. Could you elaborate on why they are obsolete? Is not like they were wiped out of the face of the earth.

Are they duplicated instead? If so can you provide more detail?

**Comment by balthild** [comment]
`Anhui`, `Anhui Province`, `Anhui Sheng`
`Fujian`, `Fujian Sheng`
`Jiangsu`, `Jiangsu Sheng`
`Liaoning`, `Liaoning Sheng`
`Shandong`, `Shandong Sheng`
`Zhejiang`, `Zhejiang Sheng`
The word _Sheng_ means _Province_ in Chinese. They refers to a same place whether with or without a _Sheng_ or a _Province_.

**Comment by javydreamercsw** [comment]
So for example keep Anhui, and delete Anhui Province, Anhui Sheng?

**Comment by javydreamercsw** [comment]
Are those the only ones?

**Comment by javydreamercsw** [comment]
It would be easier if you provide the modified file for review.

**Comment by balthild** [comment]
Yes, these province are the only ones in China. I'm a Chinese, you see.
The commit i requested ([4b07d94cd68a41a6fa77b9990523d21128ba2151](https://github.com/hiiamrohit/Countries-States-Cities-database/pull/6/commits/4b07d94cd68a41a6fa77b9990523d21128ba2151)) is the modification.

**Comment by javydreamercsw** [comment]
I'm including your changes on PR #46.

**Pull request merged**
